config/routes.rb
Rails.application.routes.draw do
  resources :films
  root to: "films#index"
  get "search", :to => "films#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord

    validates :name, :director, :launch_year, :sinopse, :rating, presence: true

    def day
        self.created_at.strftime("%b %e, %y")
    end

    def self.search(search)
        if search 
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]

  # GET /films or /films.json
  def index
    @films = Film.search(params[:search])
  end

  # GET /films/1 or /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: "Filme foi criado com sucesso" }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: "Filme foi atualizado com sucesso!" }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: "Filme foi deletado!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:name, :launch_year, :sinopse, :director, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_with(model: film) do |form| %>
  <% if film.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
      <p><%= pluralize(film.errors.count, "error") %> não permitiu a gravação do filme:</p>
      </div>

      <div class="message-body">
        <ul>
          <% film.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :ano_de_lançamento, class: "label" %>
    <%= form.number_field :launch_year, class: "input"  %>
  </div>

  <div class="field">
    <%= form.label :sinopse, class: "label" %>
    <%= form.text_area :sinopse, class: "input"  %>
  </div>

  <div class="field">
    <%= form.label :diretor, class: "label" %>
    <%= form.text_field :director, class: "input"  %>
  </div>

  <div class="field">
    <%= form.label :avaliação, class: "label" %>
    <%= form.text_field :rating, class: "input"  %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/films/edit.html.erb
<div class="columns mt-6 is-centered">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-e">Editar filme</h1>
        <b>
        <hr>
        <%= render 'form', film: @film %>

    </div>
</div>

app/views/films/index.html.erb
<% content_for :title do %>
  Filmes
<% end %>

<br>
<br>

<div class="columns is-centered">
  <%= form_with(url: '/films', method: 'get', local: true) do %>
    <%= text_field_tag(:search) %>
    <%= submit_tag("Procurar") %>
  <% end %>
</div>

<div class="columns mt-6 is-centered">

  

    <% @films.each do |film| %>
        <div class="column is-one-quarter">
          <div class="card">
            <header class="card-header">
              <p class="card-header-title"><%= film.name %></p>
            </header>
            <div class="card-content">  
              <div class="content">                    
                <span class="has-text-weight-bold">Ano de lançamento: </span><%= film.launch_year %><p></p>
                <span class="has-text-weight-bold">Sinopse: </span><%= film.sinopse %><p></p>
                <span class="has-text-weight-bold">Diretor: </span><%= film.director %><p></p>
                <span class="has-text-weight-bold">Avaliação: </span><%= film.rating %><p></p>
              </div>                
            </div>
            <div class="card-footer">
              <%= link_to 'Detalhes', film, class: "card-footer-item" %>
              <%= link_to 'Editar', edit_film_path(film), class: "card-footer-item" %>
              <%= link_to 'Deletar', film, method: :delete, data: { confirm: 'Tem certeza?' }, class: "card-footer-item" %>
            </div>
          </div>
        </div>
    <% end %>
</div>

<div class="columns is-centered mt-6">


</div>

app/views/films/new.html.erb
<div class="columns mt-6 is-centered">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-e">Novo filme</h1>
        <b>
        <hr>
        <%= render 'form', film: @film %>

    </div>
</div>

app/views/films/show.html.erb
<% content_for :title do %>
  <% @film.name %> 
<% end %>


<div class="columns mt-6 is-centered">
  <div class-"column is-one-third">
    <nav class="panel is-link">
      <p class="panel-heading">
        Nome:
          <%= @film.name %>
      </p>

      <div class="panel-block">
        Ano de lançamento: <%= @film.launch_year %>
      </div>
      
      <div class="panel-block">
        Sinopse:
          <%= @film.sinopse %>
      </div>

      <div class="panel-block">
        Diretor:
          <%= @film.director %>
      </div>

      <div class="panel-block">
        Avaliação:
          <%= @film.rating %>
      </div>

    </nav>


    <div class="columns is-mobile">
      <div class="column">
        <%= link_to 'Editar', edit_film_path(@film), class: "button is-gray" %> 
        <%= link_to 'Deletar', film_path(@film), method: :delete, data: 
        { confirm: "Tem certeza?"}, class: "button is-gray" %>
      </div>
      <div class="column">
        <!-- -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Films Rating APP</title>
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "shared/header" %>

    <% if notice.present? %>
      <div class="notification is-link is-light"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light"><%= alert %></div>
    <% end %>


    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <header class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <span class="has-text-weigth-bold is-size-4 ml-4">Catálogo de filmes</span>  
          <% end %>
          </a>
          <span class="navbar-burger" data-target="navbarMenuHeroC">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroC" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
            <%= link_to new_film_path, class: "button is-success" do %>
             <span>Novo filme</span>
            <% end%>
            </span>
          </div>
        </div>
      </div>
    </header>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <% if content_for(:title) %>
            <%= yield :title %>
        <% else %>
            Revisor filmes
        <% end %>
      </p>
    </div>
  </div>

 
</section>